// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated() || !ctx.getUserId()) {
    return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
  }
  return null;
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload, null, 2) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Martial Athletic athlete profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name, display_name, gender, date_of_birth, affiliation, about_me, subscription_tier, profile_completed").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No profile found for this account yet.");
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-competitions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_competitions_default = defineTool2({
  name: "list_competitions",
  title: "List competitions",
  description: "List competitions visible to the signed-in user, optionally filtered by status or a name search.",
  inputSchema: {
    status: z.enum(["draft", "published", "live", "completed", "expired"]).optional().describe("Filter by competition status."),
    search: z.string().trim().min(1).optional().describe("Case-insensitive match on the competition name."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum competitions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("competitions").select("id, name, status, visibility, venue, host_gym, start_date, end_date, registration_deadline, competition_type").order("start_date", { ascending: true, nullsFirst: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, competitions: data ?? [] });
  }
});

// src/lib/mcp/tools/get-competition.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_competition_default = defineTool3({
  name: "get_competition",
  title: "Get competition details",
  description: "Return one competition with its divisions and visible workouts, as the signed-in user is allowed to see them.",
  inputSchema: {
    competition_id: z2.string().uuid().describe("The competition UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ competition_id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const { data: competition, error } = await supabase.from("competitions").select("*").eq("id", competition_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!competition) return errorResult("Competition not found, or you do not have access to it.");
    const [{ data: divisions }, { data: workouts }] = await Promise.all([
      supabase.from("competition_divisions").select("id, name, team_size, max_athletes, sort_order").eq("competition_id", competition_id).order("sort_order", { ascending: true }),
      supabase.from("competition_workouts").select("id, workout_number, name, description, workout_type, scoring_type, time_cap_seconds, visibility, display_order").eq("competition_id", competition_id).order("display_order", { ascending: true })
    ]);
    return textResult({ competition, divisions: divisions ?? [], workouts: workouts ?? [] });
  }
});

// src/lib/mcp/tools/list-my-registrations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_registrations_default = defineTool4({
  name: "list_my_registrations",
  title: "List my registrations",
  description: "List competition registrations belonging to the signed-in user (as athlete or registrant).",
  inputSchema: {
    competition_id: z3.string().uuid().optional().describe("Restrict to a single competition."),
    limit: z3.number().int().min(1).max(50).default(25).describe("Maximum registrations to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ competition_id, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("athlete_registrations").select("id, competition_id, athlete_name, status, payment_status, registration_type, division_id, team_id, created_at").or(`user_id.eq.${userId},registered_by_user_id.eq.${userId}`).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (competition_id) query = query.eq("competition_id", competition_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, registrations: data ?? [] });
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool5({
  name: "get_leaderboard",
  title: "Get competition leaderboard",
  description: "Return the current leaderboard standings for a competition, grouped by division.",
  inputSchema: {
    competition_id: z4.string().uuid().describe("The competition UUID."),
    division_id: z4.string().uuid().optional().describe("Only return standings for this division.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ competition_id, division_id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_competition_leaderboard", {
      p_competition_id: competition_id
    });
    if (error) return errorResult(error.message);
    const rows = (data ?? []).filter((row) => !division_id || row.division_id === division_id);
    return textResult({ count: rows.length, standings: rows });
  }
});

// src/lib/mcp/tools/list-programs.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_programs_default = defineTool6({
  name: "list_programs",
  title: "List training programs",
  description: "List training programs the signed-in user can access (their own plus public published programs).",
  inputSchema: {
    category: z5.string().trim().min(1).optional().describe("Filter by program category."),
    level: z5.string().trim().min(1).optional().describe("Filter by difficulty level."),
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum programs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, level, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("programs").select("id, title, description, category, level, weeks_count, days_per_week, equipment, is_public, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    if (level) query = query.eq("level", level);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, programs: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "kbiuojepvucbsadesbcf";
var mcp_default = defineMcp({
  name: "martial-athletic-gateway",
  title: "Martial Athletic Gateway",
  version: "0.1.0",
  instructions: "Tools for Martial Athletic, a competition and training platform. Use `list_competitions` and `get_competition` to explore events, `get_leaderboard` for live standings, `list_my_registrations` for the signed-in athlete's entries, `list_programs` for training programs, and `get_my_profile` for the athlete profile. All calls act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_competitions_default,
    get_competition_default,
    list_my_registrations_default,
    get_leaderboard_default,
    list_programs_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
